{% set name = "Bonsu" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 49c573931057008fbd3488b54aa3c476a41d94c62461dc00798b944f5e214620
  patches:
    - 0001_remove_desktop_reference.patch
    - 0002_use_console_scripts.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --global-option=build_ext --global-option=-I$PREFIX/include
  entry_points:
    - bonsu = bonsu.interface.bonsu:bonsu

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('libXxf86vm') }}  # [linux]
    - {{ cdt('mesa-libgl') }}  # [linux]
  host:
    - pip
    - setuptools
    - python
    - pillow
    - wxpython
    - vtk
    - hdf5
    - h5py
    - numpy
    - fftw
  run:
    - python
    - pillow
    - wxpython
    - vtk
    - hdf5
    - h5py
    - numpy
    - fftw

test:
  imports:
    - bonsu
    - bonsu.docs
    - bonsu.image
    - bonsu.interface
    - bonsu.lib
    - bonsu.operations
    - bonsu.phasing
    - bonsu.sequences
  requires:   # [not win]
    - pip        # [not win]
  commands:   # [not win]
    - pip check  # [not win]

about:
  home: https://github.com/bonsudev/bonsu
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: bonsu/licence/gpl.txt
  summary: Bonsu - The Interactive Phase Retrieval Suite

extra:
  recipe-maintainers:
    - rjgildea
    - ndevenish
    - anthchirp
